
logging:
  level:
    root: debug
spring:
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017

## default settings homewizard
homewizard:
  ipaddress: "84.83.135.144:8000"
#  ipaddress: "localhost:9090"
  endpoint:
    basicinformation: "/api"
    data: "/api/v1/data"
  schedule:
    refresh:
      cron: "* * * * *"